import Header from '@@/components/header/header';
import Navbar from '@@/components/navbar/navbar';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import NextProgress from 'nextjs-toploader';
import './globals.css';
import { Providers } from './provider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<Providers>
					<NextProgress />
					<Header />
					<Navbar />
					<main className='main'>{children}</main>
				</Providers>
			</body>
		</html>
	);
}
